### ISSUE TITLE
Slim Application Error

### ISSUE THREAD

**Issue by marlevek** [hcodebr/ecommerce#13]
Olá, faço o curso php 7 completo pela udemy e não estou conseguindo avançar no curso, Volta e meia dá erro. E escrevo o código igual ao da aula, então se puder ajudar agradeço.
Agora deu esse erro:
Slim Application Error
The application could not run because of the following error:

Details
Message: Template header not found!
File: C:\XAMPP\htdocs\Ecommerce\vendor\rain\raintpl\library\Rain\Tpl.php
Line: 191
Trace
#0 C:\XAMPP\htdocs\Ecommerce\vendor\rain\raintpl\library\Rain\Tpl.php(79): Rain\Tpl->checkTemplate('header')
#1 C:\XAMPP\htdocs\Ecommerce\vendor\hcodebr\php-classes\src\Page.php(32): Rain\Tpl->draw('header')
#2 C:\XAMPP\htdocs\Ecommerce\index.php(14): Hcode\Page->__construct()
#3 [internal function]: {closure}()
#4 C:\XAMPP\htdocs\Ecommerce\vendor\slim\slim\Slim\Router.php(200): call_user_func_array(Object(Closure), Array)
#5 C:\XAMPP\htdocs\Ecommerce\vendor\slim\slim\Slim\Slim.php(1210): Slim\Router->dispatch(Object(Slim\Route))
#6 C:\XAMPP\htdocs\Ecommerce\vendor\slim\slim\Slim\Middleware\Flash.php(86): Slim\Slim->call()
#7 C:\XAMPP\htdocs\Ecommerce\vendor\slim\slim\Slim\Middleware\MethodOverride.php(94): Slim\Middleware\Flash->call()
#8 C:\XAMPP\htdocs\Ecommerce\vendor\slim\slim\Slim\Middleware\PrettyExceptions.php(67): Slim\Middleware\MethodOverride->call()
#9 C:\XAMPP\htdocs\Ecommerce\vendor\slim\slim\Slim\Slim.php(1159): Slim\Middleware\PrettyExceptions->call()
#10 C:\XAMPP\htdocs\Ecommerce\index.php(18): Slim\Slim->run()
#11 {main}

Segue arquivos php para olharem:

<?php

namespace Hcode;

use Rain\Tpl;

class Page
{
    private $tpl;
    private $options = [];
    private $defaults = [
        "data" => []
    ];

    public function __construct($opts = array())
    {

        $this->options = array_merge($this->defaults, $opts);

        $config = array(
            "tpl_dir"       => $_SERVER["DOCUMENT_ROOT"] . "/views/",
            "cache_dir"     => $_SERVER["DOCUMENT_ROOT"] . "/views-cache/",
            "debug"         => false // set to false to improve the speed
        );

        Tpl::configure($config);

        $this->tpl = new Tpl;

        $this->setData($this->options["data"]);

        $this->tpl->draw("header");
    }
    private function setData($data = array())
    {
        foreach ($data as $key => $value) {
            $this->tpl->assign($key, $value);
        }
    }

    public function setTpl($name, $data = array(), $returnHTML = false)
    {
        $this->setData($data);

        return $this->tpl->draw($name, $returnHTML);
    }
    public function __destruct()
    {
        $this->tpl->draw("footer");
    }
}

e INDEX.PHP:

<?php

require_once("vendor/autoload.php");

use \Slim\Slim;
use \Hcode\Page;

$app = new Slim();

$app->config('debug', true);

$app->get('/', function () {

	$page = new Page();

	$page->setTpl("index");
});

$app->run();

Obrigado

**Comment by hog099** [comment]
Bom Dia, Nobre

Sendo bem franco, não me recordo muito bem do projeto, mas pela mensagem ali referente "template header", a importação dos templates são em partes estruturadas, deve ter algum erro em alguma linha na importação do header, da uma revisada nessa parte.

**Comment by marlevek** [comment]
Desculpe, sou iniciante no php  não sei como verificar isso

Obter o Outlook para Android<https://aka.ms/ghei36>

________________________________

**Comment by hog099** [comment]
Os tutores, responderam as issues dentro da plataforma la?
la tbm tem uma busca de situações deve estar mais facil.

deixa o github do seu projeto aqui, tendo um tempo dou uma olhada

**Comment by marlevek** [comment]
Ok, segue link:
https://github.com/marlevek/Ecommerce.git

De: Hudson de Oliveira Ginelli <notifications@github.com>
Enviada em: quinta-feira, 18 de junho de 2020 12:02
Para: hcodebr/ecommerce <ecommerce@noreply.github.com>
Cc: Marcelo Zagonel Levek <marcelo_levek@hotmail.com>; Author <author@noreply.github.com>
Assunto: Re: [hcodebr/ecommerce] Slim Application Error (#13)


Os tutores, responderam as issues dentro da plataforma la?
la tbm tem uma busca de situações deve estar mais facil.

deixa o github do seu projeto aqui, tendo um tempo dou uma olhada

**Comment by hog099** [comment]
La na pasta vendor/hcodebr/php-classes/src/Page.php e aonde o rainTpl controi o layout, da uma olhada na linha 32 quando chama o header, o seu esta assim: 
 $this->tpl->draw("header"); 
O meu ta assim:
if ($this->options["header"] === true) $this->tpl->draw("header");

há uma validação para caso haja header ele contruir o mesmo, pois pode ser q no caso ai não o tenha e explode o erro.
Mas como disse nao me recordo, da uma olhada na doc do raintpl e aguardar um parecer dos tutores.
