### ISSUE TITLE
Erro com template do carrinho

### ISSUE THREAD

**Issue by alexsanderfer** [hcodebr/ecommerce#17]
Olá.

Eu estou com um problema no template do carrinho... 

Fiz toda a rota e configurei a classe normalmente, e antes de configurar a classe para calcular frete, o template funcionava bem. Porém agora ele me mostra esse erro. 

`Slim Application Error
The application could not run because of the following error:

Details
Code: 8
Message: Undefined variable: error
File: C:\Users\alexf\PhpstormProjects\ecommerce\views-cache\cart.20ed09ccbfa8a2ba02555f63bc57ef24.rtpl.php
Line: 26
Trace
#0 C:\Users\alexf\PhpstormProjects\ecommerce\views-cache\cart.20ed09ccbfa8a2ba02555f63bc57ef24.rtpl.php(26): Slim\Slim::handleErrors(8, 'Undefined varia...', 'C:\\Users\\alexf\\...', 26, Array)
#1 C:\Users\alexf\PhpstormProjects\ecommerce\vendor\rain\raintpl\library\Rain\Tpl.php(79): require('C:\\Users\\alexf\\...')
#2 C:\Users\alexf\PhpstormProjects\ecommerce\vendor\hcodebr\php-classes\src\Page.php(44): Rain\Tpl->draw('cart', false)
#3 C:\Users\alexf\PhpstormProjects\ecommerce\site.php(54): Hcode\Page->setTpl('cart', Array)
#4 [internal function]: {closure}()
#5 C:\Users\alexf\PhpstormProjects\ecommerce\vendor\slim\slim\Slim\Router.php(200): call_user_func_array(Object(Closure), Array)
#6 C:\Users\alexf\PhpstormProjects\ecommerce\vendor\slim\slim\Slim\Slim.php(1210): Slim\Router->dispatch(Object(Slim\Route))
#7 C:\Users\alexf\PhpstormProjects\ecommerce\vendor\slim\slim\Slim\Middleware\Flash.php(86): Slim\Slim->call()
#8 C:\Users\alexf\PhpstormProjects\ecommerce\vendor\slim\slim\Slim\Middleware\MethodOverride.php(94): Slim\Middleware\Flash->call()
#9 C:\Users\alexf\PhpstormProjects\ecommerce\vendor\slim\slim\Slim\Middleware\PrettyExceptions.php(67): Slim\Middleware\MethodOverride->call()
#10 C:\Users\alexf\PhpstormProjects\ecommerce\vendor\slim\slim\Slim\Slim.php(1159): Slim\Middleware\PrettyExceptions->call()
#11 C:\Users\alexf\PhpstormProjects\ecommerce\index.php(18): Slim\Slim->run()
#12 {main}`

Meu código no github está atualizado.

**Comment by alexsanderfer** [comment]
Resolvi
