### ISSUE TITLE
Erro

### ISSUE THREAD

**Issue by fullstackwizard** [hcodebr/ecommerce#7]
Slim Application Error
The application could not run because of the following error:

Details
Code: 2002
Message: SQLSTATE[HY000] [2002] No such file or directory
File: /var/www/html/bellabags/app/Codemy/DB/Sql.php
Line: 20
Trace
#0 /var/www/html/bellabags/app/Codemy/DB/Sql.php(20): PDO->__construct('mysql:dbname=db...', 'root', 'test')
#1 /var/www/html/bellabags/index.php(18): Codemy\DB\Sql->__construct()
#2 [internal function]: {closure}()
#3 /var/www/html/bellabags/vendor/slim/slim/Slim/Router.php(200): call_user_func_array(Object(Closure), Array)
#4 /var/www/html/bellabags/vendor/slim/slim/Slim/Slim.php(1210): Slim\Router->dispatch(Object(Slim\Route))
#5 /var/www/html/bellabags/vendor/slim/slim/Slim/Middleware/Flash.php(86): Slim\Slim->call()
#6 /var/www/html/bellabags/vendor/slim/slim/Slim/Middleware/MethodOverride.php(94): Slim\Middleware\Flash->call()
#7 /var/www/html/bellabags/vendor/slim/slim/Slim/Middleware/PrettyExceptions.php(67): Slim\Middleware\MethodOverride->call()
#8 /var/www/html/bellabags/vendor/slim/slim/Slim/Slim.php(1159): Slim\Middleware\PrettyExceptions->call()
#9 /var/www/html/bellabags/index.php(26): Slim\Slim->run()
#10 {main}

**Comment by fullstackwizard** [comment]
Corrigido. 

const HOSTNAME = "bellabags_db_1";
    const USERNAME = "root";
    const PASSWORD = "test";
    const DBNAME = "db_ecommerce";

    private $conn;

    public function __construct()
    {
		$this->conn = new \PDO(
			"mysql:dbname=".Sql::DBNAME.";host=".Sql::HOSTNAME, 
			Sql::USERNAME,
			Sql::PASSWORD
		);
    }

Coloquei o parametro da porta , pois no meu estava 3308
